//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkTeaManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUYENLIEU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NGUYENLIEU()
        {
            this.CHITIETNGUYENLIEUx = new HashSet<CHITIETNGUYENLIEU>();
        }
    
        public string MANL { get; set; }
        public string TENNL { get; set; }
        public Nullable<decimal> GIANHAP { get; set; }
        public Nullable<decimal> GIAXUAT { get; set; }
        public string MANCC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETNGUYENLIEU> CHITIETNGUYENLIEUx { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
